#!/bin/bash

# Read /etc/passwd line by line
while IFS=: read -r username password uid gid gecos home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $gecos"
done < /etc/passwd
