#!/usr/bin/env bash
# Read the /etc/passwd file line by line

while IFS=: read -r username password uid gid gecos home shell; do
    # Format and display the story for each user
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $gecos"
done < /etc/passwd
