#!/usr/bin/env bash
#This script prints Best Schoo and Hi 9 times andc one time respectively 
n=1
while [ "$n" -le 10 ]
do
    if [ "$n" -eq 9 ]
    then
	echo "Best School"
	echo "Hi"
    else
	echo "Best School"
    fi
    ((n++))
done
